public with sharing class EmailManager {
    public EmailManager() {
        public class EmailManager {
            // Public method
            public void sendMail(String address, String subject, String body) {
                // Create an email message object
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                String[] toAddresses = new String[] {address};
                mail.setToAddresses(toAddresses);
                mail.setSubject(subject);
                mail.setPlainTextBody(body);
        
                Messaging.SendEmailResult[] results = Messaging.sendEmail(
                                         new Messaging.SingleEmailMessage[] { mail });
                
                inspectResults(results);
            }
            
            // Helper method
            private static Boolean inspectResults(Messaging.SendEmailResult[] results) {
                Boolean sendResult = true;
                
        
                for (Messaging.SendEmailResult res : results) {
                    if (res.isSuccess()) {
                        System.debug('Email sent successfully');
                    }
                    else {
                        sendResult = false;
                        System.debug('The following errors occurred: ' + res.getErrors());                 
                    }
                }
                
                return sendResult;
            }
        }
    }
}
